import Header from '@/components/Header/Header'
import './globals.css'
import type { Metadata } from 'next'
import { Poppins } from 'next/font/google'
import PageAnimation from '@/components/Reusable/PageAnimation'
import Footer from '@/components/Footer/Footer'

const inter = Poppins({
   weight: ['400', '500', '600', '700', '800'],
   style: ['normal', 'italic'],
   subsets: ['latin'],
   display: 'swap',
})

export const metadata: Metadata = {
   title: '777Sense',
   description: 'Generated by create next app',
}

export default function RootLayout({ children }: { children: React.ReactNode }) {
   return (
      <html lang='en'>
         <body className={`${inter.className} pt-5 bg-[#000000]`}>
            <Header />
            <PageAnimation>
               <main>{children}</main>
            </PageAnimation>
            <Footer />
         </body>
      </html>
   )
}
